### ISSUE TITLE
[Responsive style] Logo in header becomes too narrow on smaller desktop browser windows and iPad Landscape mode

### ISSUE THREAD

**Issue by lixuna** [ligato/networkservicemesh-site#31]
How to recreate in Chrome: 
---

1. go to  https://www.networkservicemesh.io/
2. shrink browser size
3. open View > Developer > Developer Tools
4. Select iPad > toggle to landscape mode
5. Select "Responsive" > select 75%, 50%, 25%

Examples: 
<img width="996" alt="screenshot 2018-08-24 11 12 43" src="https://user-images.githubusercontent.com/11701267/44595484-b5acde80-a78e-11e8-85ca-6497c4b8444c.png">

<img width="995" alt="screenshot 2018-08-24 11 07 49" src="https://user-images.githubusercontent.com/11701267/44595415-77172400-a78e-11e8-912c-6e00da408ea0.png">

<img width="999" alt="screenshot 2018-08-24 11 07 39" src="https://user-images.githubusercontent.com/11701267/44595416-77afba80-a78e-11e8-9ee6-b644d48fe151.png">

<img width="998" alt="screenshot 2018-08-24 11 06 12" src="https://user-images.githubusercontent.com/11701267/44595417-77afba80-a78e-11e8-9802-eb523e84ac66.png">

**Comment by edwarnicke** [comment]
I thinks this is fixed by #32

**Comment by lixuna** [comment]
QA'd on https://www.networkservicemesh.io/

1. go to https://www.networkservicemesh.io/
2. shrink browser size
3. open View > Developer > Developer Tools
4. Select iPad > toggle to landscape mode
5. Select "Responsive" > select 75%, 50%, 25%

Logo looks good on all screen sizes
